# Generated by Django 4.0.3 on 2022-03-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp_admin', '0003_info_created_at_info_updated_at_sector_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='info_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='infos',
            field=models.ManyToManyField(to='cmp_admin.info'),
        ),
    ]
