# Generated by Django 4.0.3 on 2022-04-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp_admin', '0007_alter_ticket_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
